### ISSUE TITLE
[BABEL] unknown: Cannot read property 'program' of null (While processing: "base$0")

### ISSUE THREAD

**Issue by sradu** [jsbin/loop-protect#20]
It appears that receiving the second argument is broken with 7.0.0-rc3.

````
const Babel = require('@babel/standalone');
const protect = require('loop-protect');

const userCode = 'while(true) { console.log("loop") }';

const timeout = 100; // defaults to 100ms

const x = (line) => {
  throw new Error(`Bad loop on line ${line}`);
};

Babel.registerPlugin('loopProtection', protect(timeout, x));

const transform = source => Babel.transform(source, {
  plugins: ['loopProtection'],
}).code;

// rewrite the user's JavaScript to protect loops
var processed = transform(userCode);

console.log(processed);
````

returns:

````
/Work/node_modules/@babel/standalone/babel.js:95063
    throw e;
    ^

TypeError: [BABEL] unknown: Cannot read property 'program' of null (While processing: "base$0")
    at /Work/node_modules/loop-protect/dist/index.js:69:44
    at /Work/node_modules/@babel/standalone/babel.js:95096:14
````

**Comment by bonham000** [comment]
I'm still getting the same error using the setup from the README:

```
["[BABEL] unknown: Cannot read property 'program' of null (While processing: "base$0")"] "
```

Does the setup require any additional changes after the PR which closed this issue?

Versions:

```
"@babel/standalone": "^7.7.4",
"loop-protect": "^2.1.6",
```
